post http://localhost:3010/auth/validate-token
content-type: application/json

{
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVXNlcjMiLCJlbWFpbCI6ImVjb3JvbmFkb0BjcmFja3RoZWNvZGUubGEiLCJpYXQiOjE3MDEzODIxMzMsImV4cCI6MTcwMTM4MjI1M30.4paCSq6ThdI7LP8hMdQ_Al9xtuYzm2XT1LQQ6ZIhIv0"
}