version: "3.8"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - net-ms

  ms-appointment:
    container_name: ms-appointment
    build:
      context: ./
      dockerfile: ms-appointment/Dockerfile
      args:
        - BASE_DIR=ms-appointment
    restart: always
    environment:
      - APPLICATION_PORT=3030
      - RABBIT_HOST=rabbitmq:5672
      - EXCHANGE_NAME=appointment
      - EXCHANGE_TYPE=direct
    ports:
      - "3030:3030"
    depends_on:
      - rabbitmq
    networks:
      - net-ms

  ms-appointment-mx:
    build:
      context: ./
      dockerfile: ms-appointment-mx/Dockerfile
      args:
        - BASE_DIR=ms-appointment-mx
    container_name: ms-appointment-mx
    restart: always
    environment:
      - APPLICATION_PORT=3040
      - RABBIT_HOST=rabbitmq:5672
      - EXCHANGE_NAME=appointment
      - EXCHANGE_TYPE=direct
      - ROUTING_KEY=MX
      - EXCHANGE_NAME_DLQ=appointment-dlq
      - EXCHANGE_NAME_ERROR=exchange-error
      - ROUTING_KEY_DLQ=help-desk
    ports:
      - "3040:3040"
    depends_on:
      - rabbitmq
    networks:
      - net-ms

  help-desk:
    build:
      context: ./
      dockerfile: help-desk/Dockerfile
      args:
        - BASE_DIR=help-desk
    container_name: help-desk
    restart: always
    environment:
      - APPLICATION_PORT=3070
      - RABBIT_HOST=rabbitmq:5672
      - EXCHANGE_NAME=appointment-dlq
      - EXCHANGE_TYPE=direct
      - ROUTING_KEY=help-desk
    ports:
      - "3070:3070"
    depends_on:
      - rabbitmq
    networks:
      - net-ms

networks:
  net-ms:
    driver: bridge
