version: "3.8"

services:
  mysql-server:
    image: mysql:8
    container_name: mysql-server
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user-ms
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - vol-user-mysql-server:/var/lib/mysql
    networks:
      - net-user

  mysql-client:
    image: phpmyadmin:5
    container_name: mysql-client
    # restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - net-user

volumes:
  vol-user-mysql-server:

networks:
  net-user:
    driver: bridge
